config/routes.rb
Rails.application.routes.draw do
  resources :invoices, only: %i[index new create show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
end

app/models/email.rb
# frozen_string_literal: true

class Email < ApplicationRecord
  belongs_to :invoice

  def delivered!
    update(
      status: "delivered",
      delivered_at: DateTime.now
    )
  end
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :emails, dependent: :destroy

  validates(
    :reference,
    :dated_on,
    :name,
    :city,
    :county,
    :postcode,
    presence: true
  )

  def total_value
    items.sum(&:net_value)
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :invoice

  def net_value
    price * quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ApplicationController
  before_action :load_contacts

  def index
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
    @contact = Contact.find_by(id: contact_id)
    if @contact
      new_invoice_params.merge!(
        @contact.attributes.slice(
          "name", "email_address", "city", "county", "postcode"
        )
      )
    end
    @invoice = Invoice.new(new_invoice_params)

    render layout: false if @stimulus_reflex
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to invoice_path(@invoice)
    else
      render :new
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def edit
    @contact = Contact.find_by(id: contact_id)
    if @contact
      new_invoice_params.merge!(
        @contact.attributes.slice(
          "name", "email_address", "city", "county", "postcode"
        )
      )
    end
    @invoice = Invoice.find(params[:id])

    if params[:error].present?
      flash[:error] = params[:error]
    end

    render layout: false if @stimulus_reflex
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoice_params)
      redirect_to invoice_path(@invoice)
    else
      render :edit
    end
  end

  private

  def new_invoice_params
    @new_invoice_params ||= params.permit(:invoice).permit(
      :reference, :dated_on, :name, :email_address, :city, :county, :postcode
    )
  end

  def invoice_params
    @invoice_params ||= params.require(:invoice).permit(
      :reference, :dated_on, :name, :email_address, :city, :county, :postcode
    )
  end

  def contact_id
    params.dig(:invoice, :contact_id) || params[:contact_id]
  end

  def load_contacts
    @contacts = Contact.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/_email_history.html.erb
<% if invoice.emails.any? %>
  <table class="table is-fullwidth">
    <thead>
      <th>Email address</th>
      <th>Status</th>
      <th>Delivered at</th>
    </thead>
    <tbody>
      <% invoice.emails.each do |email| %>
        <tr>
          <td><%= email.sent_to %></td>
          <td><%= email.status %></td>
          <td><%= email.delivered_at %></td>
        </td>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/invoices/_items.html.erb
<div id="invoice_items" class="panel-block">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Net Value</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% invoice.items.each do |item| %>
        <tr>
          <td><%= item.description %></td>
          <td><%= item.price %></td>
          <td><%= item.quantity %></td>
          <td><%= item.net_value %></td>
          <td class="block">
            <%= button_tag(
              "",
              class: "button is-danger delete",
              data: {
                invoice_item: item.id,
                controller: "items",
                action: "click->items#remove"
              }
            ) %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <td>
        <%= button_tag(
          "Add Item",
          id: "add_item",
          class: "button",
          data: { reflex: "click->Item#show" }
        ) %>
      </td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><%= invoice.total_value %></td>
      <td>&nbsp;</td>
    </tfoot>
  </table>
</div>

app/views/invoices/edit.html.erb
<h1 class="title">Edit Invoice</h1>

<% if flash[:error].present? %>
  <article class="message is-danger">
    <div class="message-header">
      <p><%= flash[:error] %></p>
    </div>
    <div class="message-body">
      We could not send the email as the invoice has no email address
    </div>
  </article>
<% end %>

<%= form_with model: @invoice do |form| %>
  <div class="field">
    <%= form.label :contact_id, class: "label" %>
    <div class="control">
      <div class="select">
        <%= form.select(
          :contact_id,
          options_from_collection_for_select(@contacts, 'id', 'name', @contact&.id),
          { prompt: "Auto-fill address" },
        ) %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= form.label :reference, class: "label" %>
    <div class="control">
      <%= form.text_field :reference, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:reference) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:reference).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :dated_on, class: "label" %>
    <div class="control">
      <%= form.date_field :dated_on, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:dated_on) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:dated_on).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:name) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:name).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :email_address, class: "label" %>
    <div class="control">
      <%= form.email_field :email_address, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:email_address) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:email_address).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :city, class: "label" %>
    <div class="control">
      <%= form.text_field :city, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:city) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:city).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :county, class: "label" %>
    <div class="control">
      <%= form.text_field :county, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:county) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:county).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :postcode, class: "label" %>
    <div class="control">
      <%= form.text_field :postcode, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:postcode) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:postcode).join(", ") %></p>
    <% end %>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= form.button "Update invoice", class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/invoices/index.html.erb
<h1 class="title">Invoices</h1>

<div id="invoices" class="panel">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Reference</th>
        <th>Dated on</th>
        <th>Contact</th>
        <th>Total Value</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.reference %></td>
          <td><%= invoice.dated_on.strftime("%d/%m/%y") %></td>
          <td><%= invoice.name %></td>
          <td><%= invoice.total_value %></td>
          <td>
            <%= link_to "Show", invoice_path(invoice) %>
            |
            <%= link_to "Edit", edit_invoice_path(invoice) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/new.html.erb
<h1 class="title">New Invoice</h1>

<%= form_with model: @invoice do |form| %>
  <div class="field">
    <%= form.label :reference, class: "label" %>
    <div class="control">
      <%= form.text_field :reference, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:reference) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:reference).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :dated_on, class: "label" %>
    <div class="control">
      <%= form.date_field :dated_on, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:dated_on) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:dated_on).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :contact_id, class: "label" %>
    <div class="control">
      <div class="select">
        <%= form.select(
          :contact_id,
          options_from_collection_for_select(@contacts, 'id', 'name', @contact&.id),
          { prompt: "Auto-fill address" },
          data: {
            reflex: "change->Invoices#contact_selected",
            reflex_root: "form"
          }
        ) %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:name) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:name).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :email_address, class: "label" %>
    <div class="control">
      <%= form.email_field :email_address, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:email_address) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:email_address).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :city, class: "label" %>
    <div class="control">
      <%= form.text_field :city, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:city) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:city).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :county, class: "label" %>
    <div class="control">
      <%= form.text_field :county, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:county) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:county).join(", ") %></p>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :postcode, class: "label" %>
    <div class="control">
      <%= form.text_field :postcode, class: "input" %>
    </div>
    <% if @invoice.errors.key?(:postcode) %>
      <p class="help is-danger"><%= @invoice.errors.full_messages_for(:postcode).join(", ") %></p>
    <% end %>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= form.button "Create invoice", class: "button is-link" %>
    </div>
  </div>
<% end %>

app/views/invoices/show.html.erb
<h1 class="title">Invoice <%= @invoice.reference %></h1>

<div id="invoice_headers" class="breadcrumb has-dot-separator is-large">
  <ul>
    <li><button class="button mr-4 is-primary">Draft</button></li>
    <li><button class="button mx-4" data-reflex="click->SendEmail#send" >Send Now</button></li>
  </ul>
</div>

<div id="invoice_body" class="panel">
  <div class="panel-block is-flex-direction-column is-align-items-start">
    <p>
      <%= @invoice.name %>
    </p>
    <p>
      <%= @invoice.city %>
    </p>
    <p>
      <%= @invoice.county %>
    </p>
    <p>
      <%= @invoice.postcode %>
    </p>
    <p>
      <%= @invoice.email_address %>
    </p>
  </div>
  <%= render partial: "items", locals: { invoice: @invoice } %>
</div>

<div id="<%= dom_id(@invoice, "invoice_emails") %>" class="panel">
  <%= render partial: "email_history", locals: { invoice: @invoice } %>
</div>

<div id="new_item_modal">
</div>

app/views/items/_modal.html.erb
<div class="modal is-active">
  <div class="modal-background"></div>
  <div class="modal-card">
    <%= form_with model: item, url: "", class: "modal-card-body" do |form| %>
      <div class="field">
        <%= form.label :description, class: "label" %>
        <div class="control">
          <%= form.text_field :description, class: "input" %>
        </div>
        <% if invoice.errors.key?(:description) %>
          <p class="help is-danger"><%= invoice.errors.full_messages_for(:description).join(", ") %></p>
        <% end %>
      </div>
      <div class="field">
        <%= form.label :price, class: "label" %>
        <div class="control">
          <%= form.number_field :price, class: "input" %>
        </div>
        <% if invoice.errors.key?(:price) %>
          <p class="help is-danger"><%= invoice.errors.full_messages_for(:price).join(", ") %></p>
        <% end %>
      </div>
      <div class="field">
        <%= form.label :quantity, class: "label" %>
        <div class="control">
          <%= form.number_field :quantity, class: "input" %>
        </div>
        <% if invoice.errors.key?(:quantity) %>
          <p class="help is-danger"><%= invoice.errors.full_messages_for(:quantity).join(", ") %></p>
        <% end %>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <%= form.button(
            "Create item",
            class: "button is-link",
            data: {
              reflex: "click->Item#create"
            }
          ) %>
        </div>
      </div>
    <% end %>
  </div>
  <button data-reflex="click->Item#close" class="modal-close is-large" aria-label="close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusReflexDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to "Invoice-o-matic", invoices_path, class: "navbar-item" %>
      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "List", invoices_path, class: "navbar-item" %>
          <%= link_to "New", new_invoice_path, class: "navbar-item" %>
        </div>
      </div>
    </nav>

    <div class="container my-4">
      <%= yield %>
    </div>
  </body>
</html>